version: '3.3'
services:

  frontend:
    image: duckin1/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/foodgram/.env
  backend:
    image: duckin1/backend:latest
    restart: always
    volumes:
      - static_value:/app_back/static/
      - media_value:/app_back/media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
volumes:
  pgdata:
  static_value:
  media_value:
