# Generated by Django 3.2.18 on 2023-04-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
    ]
